### ISSUE TITLE
Bean validation does not work with JsonCreator

### ISSUE THREAD

**Issue by t3hk0d3** [unbroken-dome/jackson-bean-validation#1]
If deserialization is performed using `@JsonCreator` than `ConstraintViolationException` is not thrown at all.

Test case: https://gist.github.com/t3hk0d3/f0abb5ae09ae48dee36030fbb5e9f294

**Comment by tkrullmann** [comment]
Hi,
thanks for the report!

Could you please try putting the `@NotNull` constraint on the parameter as well?

When validating constructors, I can't automatically take annotations on fields into account. Since the instance is just being constructed, I'm validating the parameters to the constructor, rather than the instance itself.

**Comment by tkrullmann** [comment]
Test is verified to pass in 0.4.0 when putting the `@NotNull` constraint on the constructor parameter. Closing the issue.
